version: '3'

services:
  weather-service:
    build: .
    container_name: weather-service
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_NAME=weather
      - DB_USER=postgres
      - DB_PASS=postgres

  db:
    image: 'postgres:15.2-alpine'
    container_name: weather-service-db
    ports:
      - 5432:5432
    volumes:
      - weather-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather

volumes:
  weather-service-db:
    external: false
